services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    ports:
      - "8000:80"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    ports:
      - "3000:80"
